services:
  redis-master:
    container_name: "redis-master"
    image: 'redis:latest'
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"

  beanstalkd:
    container_name: "beanstalkd"
    image: '1maa/beanstalkd'
    ports:
      - "11300:11300"
